global:
  scrape_interval: 15s   # how often Prometheus scrapes metrics

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Your Node.js App
  - job_name: "node-app"
    static_configs:
      - targets: ["localhost:3005"]